// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okeqvidgiwgqjdskcrbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rZXF2aWRnaXdncWpkc2tjcmJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4OTc5NTIsImV4cCI6MjA3MTQ3Mzk1Mn0.AeKVmfqBhFB_LmMpna9A01Li3TB4OdVg2bwPBpyyiSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});